/// Flutter icons Smile
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Smile
///      fonts:
///       - asset: fonts/Smile.ttf
///
/// 
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Smile {
  Smile._();

  static const _kFontFam = 'Smile';

  static const IconData emo_happy = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData github_circled = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData emo_coffee = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData emo_laugh = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData github_circled_1 = const IconData(0xf09b, fontFamily: _kFontFam);
}
